### ISSUE TITLE
Current position state not saved

### ISSUE THREAD

**Issue by alikyo** [romandanylyk/PageIndicatorView#14]
Hello,

The current position of the PageIndicatorView is not saved when recreating the activity/fragment, as it is a custom view, I think it will be great if the PageIndicatorView could restore it state itself.

Workaround : Implement the onSaveInstanceState (Activity/Fragment) to store the PageIndicatorView current position and set it on the onCreate method.

Br.

**Comment by romandanylyk** [comment]
Fixed in version 1.0.0
