### ISSUE TITLE
RTL Support

### ISSUE THREAD

**Issue by alikyo** [romandanylyk/PageIndicatorView#15]
As an enhancement :) it will be great if we could have the RTL support.
exemple of RTL viewPager (https://github.com/diego-gomez-olvera/RtlViewPager).

Currently I am just rotating the PageIndicator :p

**Comment by romandanylyk** [comment]
nice enhancement
will be released soon

**Comment by mhelmi** [comment]
is there Any updates about rtl support? now ViewPager2 support rtl.
