### ISSUE TITLE
Invisible pageIndicator issue

### ISSUE THREAD

**Issue by manijak** [romandanylyk/PageIndicatorView#17]
Hi again @romandanylyk. Referring to an earlier case https://github.com/romandanylyk/PageIndicatorView/issues/7

If I upgrade to version 7 or higher, I get invisible indicator in my views. I get no crashes or exceptions. All properties are set, I get proper page count as well. ViewPager works fine. I can also see that the pageIndicator instance has a parent view. But still, nothing is shown. 

Do you perhaps have any idea what this might be? I should say that my views & layouts are defined in code only, no xml. Does pageIndicator only work with RelativeLayout or can we use anything? 

Version 6 and earlier works without issues.

**Comment by romandanylyk** [comment]
Hi,
while using PageIndicatorView you can use any of layout, it does not depends on it.
To fix visibility issue, can you please specify what setters in customisation do you use in java code? This issue could be related to it.

Thanks.

**Comment by manijak** [comment]
For example, I use the following settings:
`selectedColor = #ffffff`
`unselectedColor = #33ffffff`
`animationType = com.rd.animation.AnimationType.COLOR`
`animationDuration = 500`

Trimmed code example (NativeScript code):
```
_viewPager = new android.support.v4.view.ViewPager(this._context);
_viewPager.setId(this._androidViewId);
        
_pageIndicatorView = new com.rd.PageIndicatorView(this._context);
_pageIndicatorView.setId(this._indicatorViewId);

_viewPager.setAdapter(new CarouselPagerAdapterClass(this));
_viewPager.setOnPageChangeListener(new CarouselPageChangedListenerClass(this));
        
_pagerIndicatorLayoutParams = parentViewContainer.getLayoutParams();
_pagerIndicatorLayoutParams.height = android.support.v4.view.ViewPager.LayoutParams.WRAP_CONTENT;
_pagerIndicatorLayoutParams.width = android.support.v4.view.ViewPager.LayoutParams.WRAP_CONTENT;
_pagerIndicatorLayoutParams.setMargins(0, 0, 0, 20);
_pagerIndicatorLayoutParams.gravity = android.view.Gravity.BOTTOM;

_pageIndicatorView.setViewPager(this._viewPager);
_pageIndicatorView.setCount(this._childrenCount);
_pageIndicatorView.setSelection(this.selectedPage);
```

As I mentioned before, the same code works with version 6.0.

**Comment by romandanylyk** [comment]
Thanks, I will try to figure out what's wrong with it.

**Comment by romandanylyk** [comment]
Looks like I found whats was wrong.
Please see latest version for fix. (Will be released soon)

**Comment by manijak** [comment]
@romandanylyk  Thanks for the last update! It works now. 

There is another issue now, the indicators are all aligned to the left of the view. Cannot seem to center them.

**Comment by manijak** [comment]
Never mind, fixed. LayoutParams was off. :) Thanks again!

**Comment by romandanylyk** [comment]
Thank you for reporting issues. 
Glad it helped
