### ISSUE TITLE
Question: How does it work?

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [romandanylyk/PageIndicatorView#2]
Without diving into the code, can you please explain shortly how does it work?
Why does it have minSdk 15 ?

**Comment by romandanylyk** [comment]
PageIndicarView extends View, so basically it's working based on canvas drawing.

**Comment by alashow** [comment]
Supporting at least 14 would be great.

**Comment by romandanylyk** [comment]
All the animation works by `ValueAnimator` added in API 11. For increasing stability for now it has minSdk 15 and wasn't tested on lower API yet.
It future releases it will be tested on API 11 and if it is ok, minSdk will be decreased.

**Comment by AndroidDeveloperLB** [comment]
Maybe not 11, but 14 is still a lot more popular than 11-13, no?

**Comment by romandanylyk** [comment]
I will work on it as soon as possible

**Comment by romandanylyk** [comment]
> So you have some formula for the transition in between pages, to draw via the canvas?
It's a bit simpler that formula actually, because `viewPager `has `addOnPageChangeListener ` and with a bit of math I do all the calculations to draw indicators

**Comment by AndroidDeveloperLB** [comment]
What's the math of it?

Also, thank you for this library and testing on API 14 .

**Comment by romandanylyk** [comment]
For interactive animation all the math is in `onPageScroll `method.
As so initial drawing it's based on view size and count, you can see it in `drawIndicatorView `method.

**Comment by AndroidDeveloperLB** [comment]
I guess there is no way to understand it without diving, then :)

**Comment by romandanylyk** [comment]
If explaining on word, I get count of indicator that user set, than knowing it's radius and padding measure view size. Then after calculating general view size I just draw circles on canvas one by one.

Interactive animation is a bit interesting. It's is performing by frames. So thanks to `ValueAnimation` I set start and end value and it returns me that value several times so I can redraw my view based on than value every time that value changed - that's how animation is performing.

**Comment by AndroidDeveloperLB** [comment]
But it has a worm-like transition. Do you draw circles there, one after another?

**Comment by romandanylyk** [comment]
It's a bit tricky :)
Worm animation is not actually a circle - it's a rectangle with rounded corners that changes its width all the way.

**Comment by AndroidDeveloperLB** [comment]
oh, makes sense.

**Comment by romandanylyk** [comment]
Hope it helped you to understand how it works. 
I appreciate that you are one who interested ^)

**Comment by AndroidDeveloperLB** [comment]
What do you mean? You know me? You know my work/repositories/apps?

**Comment by romandanylyk** [comment]
You just was the first one, who asked :)

**Comment by AndroidDeveloperLB** [comment]
Oh ok. You are welcomed to check them if you wish:
https://github.com/AndroidDeveloperLB?tab=repositories
