### ISSUE TITLE
Switching between pages

### ISSUE THREAD

**Issue by iturricf** [romandanylyk/PageIndicatorView#23]
Hi guys! awesome job! I just added PageIndicatorView to my ViewPager and it works great!

I tried to find a way to switch between the pages by touching indicators but no success. Is there a simple way o achieve this?

**Comment by romandanylyk** [comment]
Hi, thanks for a feedback.
Unfortunately PageIndicatorView does not support click on single indicator for now, so It could be in future releases.
I'll mark this issues as enhancement, to make it in new version.

Thanks.

**Comment by westlinkin** [comment]
Any progress or solution?

**Comment by romandanylyk** [comment]
This enhancement is added in latest release (1.0.0)
