### ISSUE TITLE
Customize XML PageIndicator

### ISSUE THREAD

**Issue by douglasalipio** [romandanylyk/PageIndicatorView#24]
Hi, 

Can I customize the circle icon for a line? Something like that

[](url)
![screenhunter_01 feb 17 20 37](https://cloud.githubusercontent.com/assets/896757/23088245/cef38eba-f561-11e6-995b-60ce6a460fe6.jpg)

Regards,

**Comment by romandanylyk** [comment]
Hi, PageIndicatorView does not support line indicators for now,
it could be added in future releases. I'll make this issues as enhancement.

Thanks
