### ISSUE TITLE
Can't set view pager in xml

### ISSUE THREAD

**Issue by OlegTarashkevich** [romandanylyk/PageIndicatorView#25]
Hi there,
@romandanylyk  I found that I can't set viewPager for indicator in xml, if indicator is placed before viewPager.
Please fix it.

app:piv_viewPager="@id/view_pager"

But it does work if set indicator after viewPager or I set it programmatically.

Thank you.

**Comment by osrl** [comment]
I also can't set it from xml. `if (context instanceof Activity)` this line returns false. In my case context is instanceof ContextThemeWrapper not Activity. I think you should use [http://stackoverflow.com/a/32973351/1120126](this) to get the activity.

**Comment by romandanylyk** [comment]
Hi,
thanks for reporting issue.
Can you please specify where you declare a PageIndicatorView (java and xml is possible) so I can investigate this issue more detailed.

Thanks.

**Comment by OlegTarashkevich** [comment]
@romandanylyk Seems we have difference in issues between my and @osrl. I'm talked about sequence of declaration pageindicator in xml.

**Comment by romandanylyk** [comment]
@OlegTarashkevich Hi,
while declaring PageIndicatorView before ViewPager in layout, and specifying view_pager_id attribute, you should declare it with "+", please see example below.

`attrs:piv_viewPager="@+id/viewPager"`

Thanks.
