### ISSUE TITLE
doesn't work properly with partially size

### ISSUE THREAD

**Issue by OlegTarashkevich** [romandanylyk/PageIndicatorView#26]
Hi @romandanylyk , 
I've created custom FragmentPagerAdapter with width of page = 0.9f.

```
public float getPageWidth(int position) {
        return .9f;
    }
```

```
app:piv_padding="5dp"
app:piv_radius="5dp"
app:piv_animationType="worm"
app:piv_dynamicCount="true"
app:piv_interactiveAnimation="true"
```

As the result indicator can't scroll to the final position. Last point should be circle, not oval. Please look at the screenshot.

Please fix it.
![device-2017-02-19-193701](https://cloud.githubusercontent.com/assets/13828110/23104447/3bcc90f8-f6df-11e6-8264-a6d39d2bc331.png)

Thank you.

**Comment by romandanylyk** [comment]
You should better use a ViewPager padding in this case. 
```
viewpager.setClipToPadding(false)
viewpager.setPadding(left, 0, right, 0)
```
And here is why:
while making a page width other than 1.0f, ViewPager does not return right offset value. For example if PageWidth will be 0.5f, 2 pages at the same time will be displayed, so there will be no right way to display indicator in right place.

Let me know if this helps.

**Comment by OlegTarashkevich** [comment]
@romandanylyk It does work, but I have another expected behaviour. I have only two pages. 
If I set padding as you're showed - I will have padding for both pages. In my situation I need right padding for first page and left padding for second page.

Can you please include my name @OlegTarashkevich when you post any message to me, it will help me to get a notification.

Thank you.

![device-2017-03-01-160305](https://cloud.githubusercontent.com/assets/13828110/23460915/a7f1c788-fe98-11e6-8c08-5970206a2000.png)

**Comment by romandanylyk** [comment]
@OlegTarashkevich Hi,
Unfortunately ViewPager does not support this kind of padding with returning a right offset value.
