### ISSUE TITLE
Set visibility when count is one

### ISSUE THREAD

**Issue by osrl** [romandanylyk/PageIndicatorView#28]
It would be nice to have an xml attribute like `visibilityWhenCountOne`(or a better name) with the choices of "visible" "gone" and "invisible"

**Comment by pro100svitlo** [comment]
I also waiting for this function! 
in fact I think this must be default behaviour - if pager has only one child, set indicator "invisible" or "gone".

**Comment by romandanylyk** [comment]
Added in `dev` branch, stay tuned for a new lib version.
Thanks for a feedback.

**Comment by shaziln** [comment]
"gone“ is better ,if PageIndicator is between viewPager and another view, “invisible” will create a blank space can not control
