### ISSUE TITLE
Trouble with "slide" animation type

### ISSUE THREAD

**Issue by terrakok** [romandanylyk/PageIndicatorView#32]
For Slide animation i found problem.
1) PagerAdapter is empty
2) load something from network
3) set data to adapter
4) call ```pageIndicatorView.setCount(adapter.getCount()); //because indicator not update automaticaly```
5) indicator looks broken (but after first slide all OK)

![](https://habrastorage.org/files/544/734/1aa/5447341aa1c14958b18ce21be5219974.png)

**Comment by romandanylyk** [comment]
@terrakok Hi,

> because indicator not update automaticaly
To make indicators update automatically with viewpager count, you can specify
` attrs:piv_dynamicCount="true" ` attribute.

However, there was a bug with steps you specified, so thanks for a feedback.
This issue is fixed now on `dev` branch, so it will be released soon.

Thanks.

**Comment by jemshit** [comment]
@romandanylyk Hi, i am encountering same issue, half visible first indicator. Here is xml:
```xml
 <com.rd.PageIndicatorView
        android:id="@+id/pager_indicator"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:padding="2dp"
        app:piv_animationType="worm"
        app:piv_dynamicCount="true"
        app:piv_interactiveAnimation="true"
        app:piv_orientation="horizontal"
        attrs:piv_padding="12dp"
        attrs:piv_radius="4dp"/>
```

and code:
```java
 adapter = SomeAdapter(supportFragmentManager)
        viewPager.adapter = adapter
        viewPager.offscreenPageLimit = 2
        pager_indicator.setViewPager(viewPager)
```

Pager size changes when adapter size changes : 
```java
adapter.updateAdapterSize(size)
adapter.notifyDataSetChanged()
```
But first indicator is broken as image on above

**Comment by jemshit** [comment]
Played with piv_padding, piv_radius, and activity xml layout, now it works without problem. Changed nothing else o.O
