### ISSUE TITLE
Why dependent on appcompat-v7?

### ISSUE THREAD

**Issue by nantofu** [romandanylyk/PageIndicatorView#33]
I find that the pageindicatorview module's dependencies imported the appcompat-v7 library. But I can find any importion in all the java files in this module. So, Why are you dependent on this library?

**Comment by romandanylyk** [comment]
Hi @nantofu,

In `PageIndicatorView` library I do use support annotation, so this why there are `appcompat-v7` in dependencies.

Thanks.
