### ISSUE TITLE
Current page visual selection

### ISSUE THREAD

**Issue by fAns1k** [romandanylyk/PageIndicatorView#36]
it would be good to select visually current selected item, f.e. make it bigger then the others, or smaller, etc.

Thank you.

**Comment by romandanylyk** [comment]
@fAns1k Hi,
maybe "animationType = SCALE" fill fit nicely in your case.

**Comment by StuStirling** [comment]
Maybe there is a requirement to reverse the scale so that the selected page is smaller than the others? `AnimationType.SCALE_SMALL` perhaps?

**Comment by romandanylyk** [comment]
@StuStirling Hi,
Unfortunately there no such option for now.
I'll leave this issue as enhancement to implement such animation in future releases.

**Comment by romandanylyk** [comment]
Added new animation type called `SCALE_DOWN`, currently in `dev` branch.
Will be merged to `master` and released soon.
Closing this issue.
