### ISSUE TITLE
It's not possible to change the color of the indicator.

### ISSUE THREAD

**Issue by micrcx** [romandanylyk/PageIndicatorView#37]
Hi,

I slightly changed your sample: were added two lines to the initViews function.
The color of the indicators does not change. Can you tell me what the problem?

    private void initViews() {
        HomeAdapter adapter = new HomeAdapter();
        adapter.setData(createPageList());

        ViewPager pager = (ViewPager) findViewById(R.id.viewPager);
        pager.setAdapter(adapter);

        PageIndicatorView indicatorView = (PageIndicatorView) findViewById(R.id.pageindicatorview);
        indicatorView.setViewPager(pager);
        indicatorView.setOrientation(Orientation.VERTICAL);
//<<<< New lines >>>>
        indicatorView.setUnselectedColor(R.color.google_green);
        indicatorView.setSelectedColor(R.color.google_yellow);
    }

Regards,
Michael K

**Comment by romandanylyk** [comment]
@micrcx Hi,
if you want to change color of `PageIndicatorView`, you should do it by following:

```java
indicatorView.setUnselectedColor(getResources().getColor(R.color.google_green));
indicatorView.setSelectedColor(getResources().getColor(R.color.google_yellow));
```

(You can also change indicators color in xml)
Thanks.
