### ISSUE TITLE
Reverse animation

### ISSUE THREAD

**Issue by sudikrt** [romandanylyk/PageIndicatorView#38]
Hey its a nice library.
I m using this with recycler view, it works fine when i scroll forward. But when i scroll backward then animation wont happen 
I m using this method setSelection(POSITION); to set the dot.
But when i use this method to set the previous dot (say i scrolled reverse) the animation was not proper.
Could you help me on this.

Thanks

**Comment by romandanylyk** [comment]
@sudikrt Hi,
can you please provide more details how can I reproduce it?
Also what type of animation do you use?

Thanks

**Comment by romandanylyk** [comment]
Closing this due to lack of details and not able to reproduce the issue.
