### ISSUE TITLE
android:padding doesn't work

### ISSUE THREAD

**Issue by mokkun** [romandanylyk/PageIndicatorView#39]
Setting the `android:padding` property into a `PageIndicatorView` has no effect.
I'm aware of the `app:piv_padding` property, but that serves a different purpose. What I desire is to set a padding around the page indicators.
```
<com.rd.PageIndicatorView
            android:layout_width="wrap_content"
            android:layout_height="24dp"
            android:background="@android:color/white"
            android:padding="24dp"
            app:piv_animationType="slide"
            app:piv_viewPager="@id/view_pager"/>
```

I believe the same would apply to the other `android:padding` variants, such as `android:paddingStart`, `android:paddingEnd`, etc

**Comment by romandanylyk** [comment]
Fixed in incoming version.
Commit #: 8c91c97e8e3896e19641816c8090d0e4c4fef21b
