### ISSUE TITLE
set color

### ISSUE THREAD

**Issue by xyy465925800** [romandanylyk/PageIndicatorView#41]
pageIndicatorView.setUnselectedColor(R.color.bg_white);
		pageIndicatorView.setSelectedColor(R.color.bg_red); 不起作用啊

**Comment by romandanylyk** [comment]
Hi @xyy465925800,
you should not set colorID here, but color instead:
```java
pageIndicatorView.setSelectedColor(getResources().getColor(R.color.bg_red));
```
Thanks.
