### ISSUE TITLE
setSelection(position) problem

### ISSUE THREAD

**Issue by hymanme** [romandanylyk/PageIndicatorView#42]
i have used it without ViewPager,just call  setSelection(position) ,and then it will change postion to target position,but at last it must return back to postion 0. amazing。

**Comment by hymanme** [comment]
it will be ok when use animation WORM and NONE

**Comment by romandanylyk** [comment]
@hymanme, don't quite understand your issue.
Can you please describe it more detailed?

**Comment by romandanylyk** [comment]
Closing this issue duo to lack of information
