### ISSUE TITLE
Failed to resolve: annotationProcessor

### ISSUE THREAD

**Issue by miankhalid** [romandanylyk/PageIndicatorView#44]
This is my grade file:
https://github.com/edx/edx-app-android/blob/a0a6b44845a438d28bb415250a8364317989d407/OpenEdXMobile/build.gradle

I just added these lines to use this awesome library:

````java
    // For the optional Nullable annotation
    compile 'com.android.support:support-annotations:25.3.1'

    compile 'com.romandanylyk:pageindicatorview:0.2.0@aar'
    compile 'com.android.support:support-compat:25.3.1'
    compile 'com.android.support:support-core-ui:25.3.1'
````

But getting the said error i.e. `Failed to resolve: annotationProcessor`.

**Comment by romandanylyk** [comment]
@miankhalid Hi,
have you tried including library by single line
`compile 'com.romandanylyk:pageindicatorview:0.2.0'` ?

**Comment by miankhalid** [comment]
@romandanylyk yeah tried that too, same problem.

**Comment by miankhalid** [comment]
anything else that comes into your mind to solve this problem @romandanylyk ?

**Comment by romandanylyk** [comment]
@miankhalid it's a pretty weird issue,
alternatively you can try to remove 
` compile 'com.android.support:support-annotations:25.3.1'` from your `build.gradle` file and include `PageIndicatorView` by
`compile 'com.romandanylyk:pageindicatorview:0.2.0'` that already contain dependency on annotations library.

**Comment by lbx2015** [comment]
adding exclude group in your gradle file as following:
 compile('com.github.bumptech.glide:glide:4.2.0', {
        exclude group: 'com.android.support', module: 'support-annotations'
    })
