### ISSUE TITLE
how to add PageIndicatorView dependancy in nativescript 

### ISSUE THREAD

**Issue by RakeshKW** [romandanylyk/PageIndicatorView#47]
i am making android app using nativescript ...so please tell me how to add this dependancy.
Because nativescript carousal plugin is not working and its showing  "cannot read property 'PageIndicatorView' of undefined,undefined"

**Comment by bradmartin** [comment]
The plugin below exposes this library for NativeScript android apps 👍 

https://github.com/manijak/nativescript-carousel

**Comment by romandanylyk** [comment]
@RakeshKW, I think @bradmartin answered on your question :)
