### ISSUE TITLE
how set size for circle image

### ISSUE THREAD

**Issue by mahdighaemi123** [romandanylyk/PageIndicatorView#48]
hi
i not good at engilish
how set size for view pager inficator
thanks

**Comment by romandanylyk** [comment]
Hi @mahdighaemi123 
to set a size for a` PageIndicatorView` use those methods:
`setRadius(int radiusDp)` - to set indicator radius
`setPadding(int paddingDp)` - to set a padding between each indicator.
Hope it helps!
