### ISSUE TITLE
Dynamic count = false / custom  piv_count not possible

### ISSUE THREAD

**Issue by rodentooth** [romandanylyk/PageIndicatorView#56]
I have 5 fragments, of which only 3 are displayed, the others will be skipped. But the piv always shows 5 dots:

        <com.rd.PageIndicatorView
            android:id="@+id/pageIndicatorView"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_alignParentEnd="false"
            android:layout_centerHorizontal="true"
            android:layout_centerVertical="false"
            android:layout_marginTop="20dp"
            android:elevation="5dp"
            app:piv_count="3"
            app:piv_dynamicCount="false"
            app:piv_unselectedColor="#000000" />

**Comment by romandanylyk** [comment]
@rodentooth  if you set` ViewPager` to a `PageIndicatorView`it will get items count and selected items from it.
So while having a skipped (hidden) fragments you don't want to select, you will need to operate with select dot manually via `setSelection` method.
