### ISSUE TITLE
ReadMe Typo

### ISSUE THREAD

**Issue by searchy2** [romandanylyk/PageIndicatorView#61]
Attribute cannot be found error when using sample XML code provided in ReadMe. 
Instead of:
`attrs:piv_viewPager="@id/viewPager"`

It should be:
`attrs:piv_viewPager="@+id/viewPager"`

**Comment by searchy2** [comment]
Fixed in PR #63

**Comment by romandanylyk** [comment]
@searchy2 Thanks, merged
