### ISSUE TITLE
Move PageIndicator if more Data available in ViewPager

### ISSUE THREAD

**Issue by aesadde** [romandanylyk/PageIndicatorView#64]
Hi,

I've created a PageIndicator as follows:
```
        <com.rd.PageIndicatorView
            android:id="@+id/background_piv"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_toEndOf="@id/opcamera"
            android:layout_centerHorizontal="true"
            android:layout_toStartOf="@+id/background_tv"/>
```

My `ViewPager` contains around 50 elements, the `PageIndicator` works fine for the first `X` pages (where `X` is the number of dots that the PageIndicator can show on Screen) but as soon as I display the page `X+1` the `PageIndicator` doesn't scroll to the right, i.e. it stops being updated.

I'm sure I'm doing something wrong so any help will be greatly appreciated :D

**Comment by romandanylyk** [comment]
@aesadde Hi
do you mean that `PageIndicatorView` displays too many indicators that they can't fit in a screen width? If so, currently `PageIndicatorView` if focusing on low pages count, so they can easily fits in one row. 
Later on, `PageIndicatorView` will support scrolling, basically like in Instagram app.

**Comment by aesadde** [comment]
@romandanylyk thanks for the speedy reply!

Yes, I think I mean scrolling. I have a long list of pages to display but once I get past the rightmost page shown on the indicator, the indicator stops working (i.e. no dots gets highlighted!)

I'll keep an eye for the next release then :)

**Comment by romandanylyk** [comment]
@aesadde oh than you are one of that people who are waiting for scrolling feature ^)
Unfortunately recently I have not enough free time to complete this feature, so it is in todo list.

**Comment by aesadde** [comment]
@romandanylyk sure no problem. I'll try to figure something out myself and will send a PR if I manage something soon ;)
