### ISSUE TITLE
java.lang.IllegalStateException Bug with recyclerview

### ISSUE THREAD

**Issue by kushmangal** [romandanylyk/PageIndicatorView#66]
I am getting the following error when I have implemented the library within a recyclerview that contains several viewpagers.

W/System.err: java.lang.IllegalStateException: Observer com.rd.PageIndicatorView$1@e14d923 was not registered.
11-01 17:12:54.177 16657-16657/com.app W/System.err:     at android.database.Observable.unregisterObserver(Observable.java:69)
11-01 17:12:54.177 16657-16657/com.app W/System.err:     at android.support.v4.view.PagerAdapter.unregisterDataSetObserver(PagerAdapter.java:305)
11-01 17:12:54.177 16657-16657/com.app W/System.err:     at com.rd.PageIndicatorView.unRegisterSetObserver(PageIndicatorView.java:622)
11-01 17:12:54.178 16657-16657/com.app W/System.err:     at com.rd.PageIndicatorView.onDetachedFromWindow(PageIndicatorView.java:61)
11-01 17:12:54.178 16657-16657/com.app W/System.err:     at android.view.View.dispatchDetachedFromWindow(View.java:15668)
11-01 17:12:54.178 16657-16657/com.app W/System.err:     at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3183)
11-01 17:12:54.178 16657-16657/com.app W/System.err:     at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3183)
11-01 17:12:54.178 16657-16657/com.app W/System.err:     at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3183)
11-01 17:12:54.179 16657-16657/com.app W/System.err:     at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3183)
11-01 17:12:54.179 16657-16657/com.app W/System.err:     at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3183)
11-01 17:12:54.179 16657-16657/com.app W/System.err:     at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3183)
11-01 17:12:54.179 16657-16657/com.app W/System.err:     at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3183)
11-01 17:12:54.179 16657-16657/com.app W/System.err:     at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3183)
11-01 17:12:54.179 16657-16657/com.app W/System.err:     at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3183)
11-01 17:12:54.179 16657-16657/com.app W/System.err:     at android.view.ViewRootImpl.dispatchDetachedFromWindow(ViewRootImpl.java:3293)
11-01 17:12:54.179 16657-16657/com.app W/System.err:     at android.view.ViewRootImpl.doDie(ViewRootImpl.java:6001)
11-01 17:12:54.180 16657-16657/com.app W/System.err:     at android.view.ViewRootImpl.die(ViewRootImpl.java:5978)
11-01 17:12:54.180 16657-16657/com.app W/System.err:     at android.view.WindowManagerGlobal.removeViewLocked(WindowManagerGlobal.java:446)
11-01 17:12:54.180 16657-16657/com.app W/System.err:     at android.view.WindowManagerGlobal.removeView(WindowManagerGlobal.java:384)
11-01 17:12:54.180 16657-16657/com.app W/System.err:     at android.view.WindowManagerImpl.removeViewImmediate(WindowManagerImpl.java:126)
11-01 17:12:54.180 16657-16657/com.app W/System.err:     at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:4445)
11-01 17:12:54.180 16657-16657/com.app W/System.err:     at android.app.ActivityThread.-wrap6(ActivityThread.java)
11-01 17:12:54.180 16657-16657/com.app W/System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1618)
11-01 17:12:54.180 16657-16657/com.app W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:102)
11-01 17:12:54.180 16657-16657/com.app W/System.err:     at android.os.Looper.loop(Looper.java:154)
11-01 17:12:54.180 16657-16657/com.app W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:6369)
11-01 17:12:54.180 16657-16657/com.app W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
11-01 17:12:54.181 16657-16657/com.app W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
11-01 17:12:54.181 16657-16657/com.app W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)

**Comment by hiteshsarsava** [comment]
i am also getting this isuue much...

**Comment by romandanylyk** [comment]
This issue should be fixed in newer 1.0.1 library version
