### ISSUE TITLE
bug when added in recyclerview

### ISSUE THREAD

**Issue by Vichy97** [romandanylyk/PageIndicatorView#68]
I have a list of cardviews in a recyclerview. Each card view has its own viewpager indicator but when you swipe one of them, all the indicators change position (the corresponding viewpagers dont change position).

**Comment by romandanylyk** [comment]
@Vichy97 this is not an issue of PageIndicatorView, please read [usage sample section](https://github.com/romandanylyk/PageIndicatorView#usage-sample) of readme file, you can find there issues related to id conflicts.
