### ISSUE TITLE
setProgress() causes indicator to freezes its position without reaching to the next indicator position

### ISSUE THREAD

**Issue by siralam** [romandanylyk/PageIndicatorView#70]
Firstly, thanks for the update to v1.0.0 so promptly!

I started to test for setProgress() immediately. However I find some problem here:

When I am scrolling from page1 to page2, I call
```
indicatorView.setProgress(1, progress);
```
`progress` is the value from `onPageScrolled()`.

And when I release my finger, onPageSelected() is triggered and therefore the following:
```
indicatorView.setSelection(1);
```

And after `indicatorView.setSelection(1)` is called, I didn't called `setProgress()` anymore.

So what I expect is:  
before `setSelection()` is called, the indicator will shift, following my finger;  
after `setSelection()` is called, the indicator will go to the final position (The next dot) automatically.

But now it freezes at the middle like this:  

![screenshot_2017-12-21-11-39-38-503_com asksira loopingviewpagerdemo](https://user-images.githubusercontent.com/28033467/34239711-301c5d1a-e644-11e7-9a7d-999818a46776.PNG)

**Comment by romandanylyk** [comment]
@siralam Hi,
first of all if you are using `setProgress` to smoothly change selected indicator, you should use it from start to the end process, even if you release your finder, `ViewPager` will call `onPageScrolled` until new page will be selected, so you should not use `setSelection` in this case.

Secondly, `setProgress` receive progress [0, 1f) and `selectingPosition` values as parameters. Those are not untouched values straight from `ViewPager`'s `onPageScrolled`
Progress value in range [0 - 1] to specify state of animation while selecting new circle indicator. ViewPager provides offset, it is not the same as progress, please look for getProgress method [here](https://github.com/romandanylyk/PageIndicatorView/blob/master/pageindicatorview/src/main/java/com/rd/utils/CoordinatesUtils.java).
Once progress will be 1, a new selected position will be selected. 

So the main rule here, to do not combine `setProgress` and `setSelection` at the same time. Once you are using interactive progress, use `setProgress`, once it is false, use `setSelection`. 
Note: you can also use `setSelected` method to select indicator without any animation.

**Comment by siralam** [comment]
> So the main rule here, to do not combine setProgress and setSelection at the same time.

I think I understand what you are thinking.  
But I encountered a problem - If user does not wait for the next page to settle, and flipped to another page, bug may occurs.

This is because progress never reaches 0 or 1, and the "memorized" position of indicator does not update. After `setProgress()` is finished, it stays at the original position...

Do you have any suggestion for this?

**Comment by romandanylyk** [comment]
Even if user fast scrolls `ViewPager` `setProgress` method should always reach progress 1 after new page if selected. So it should not produce any bugs with it.

**Comment by siralam** [comment]
Do you mean I should manually call `setProgress(selectingPosition, 1)` if I detected that user is fastScrolling?

Because `onPageScrolled()` won't actually reach offset 1 if user fast scroll.

**Comment by siralam** [comment]
> Do you mean I should manually call setProgress(selectingPosition, 1)

I finally managed to do the above and it works perfectly now.  
Although as I user of your library, I question such UX; but I think it is good enough as long as it works now.

Thanks!
