### ISSUE TITLE
How to programmatically change color (selected/unselected) of indicator

### ISSUE THREAD

**Issue by c0state** [romandanylyk/PageIndicatorView#77]
I'm looking to change the color of the indicator via some dynamic logic in my application but the following call pattern doesn't seem to work:
```
this.pageIndicatorView.setSelectedColor(Color.BLACK);
this.pageIndicatorView.invalidate();
```

If I initiate a touch event on the view pager, then the indicator picks up the event and changes the color that I set above. 

Any idea what I'm missing or is this an unforeseen limitation?

I'm currently using a hack of setting the viewpager's current item to n+1 and then back to n to force the color change after the `setSelectedColor()` call.

**Comment by yccheok** [comment]
I have the same issues as well.


        viewPager.addOnPageChangeListener(new ViewPager.OnPageChangeListener() {
            @Override
            public void onPageScrolled(int i, float v, int i1) {

            }

            @Override
            public void onPageSelected(int i) {
                updatePageIndicatorView(themes, pageIndicatorView, i);
            }

            @Override
            public void onPageScrollStateChanged(int i) {

            }
        });
        
        private void updatePageIndicatorView(Theme[] themes, com.rd.PageIndicatorView pageIndicatorView, int selection) {
            Theme theme = themes[selection];
            pageIndicatorView.setSelection(selection);
            Context context = getContext();
            final int selectedTextColor = ContextCompat.getColor(context, theme.selectedTextColorResourceId);
            final int normalTabColor = ContextCompat.getColor(context, theme.normalTabColorResourceId);

            pageIndicatorView.post(() -> {
                pageIndicatorView.setSelectedColor(selectedTextColor);
                pageIndicatorView.setUnselectedColor(normalTabColor);
            });
        }

When pageIndicatorView.setSelectedColor is called in onPageSelected, it is already too late. setSelectedColor doesn't work (Still using previous color), but setUnselectedColor do reflect latest color.

**Comment by c0state** [comment]
It seems to be an issue with the "scale" type page indicators. From a quick call trace, the old color is being retrieved from the `ScaleAnimationValue` and reused in the `ScaleDrawer.draw()` method. 

The `slide` page indicator type doesn't seem to have this issue. Not sure if any of the others do as well. I changed my page indicator type to `slide` for now to get around this.
