### ISSUE TITLE
How to catch the click event of the pageindicator?

### ISSUE THREAD

**Issue by talent-webmobiledeveloper** [romandanylyk/PageIndicatorView#82]
Hi.
When using this component, I wanna to catch the click event of the page indicator.
So to click the (n)th circle, the app has to display (n)th page.
How could I do this?

Thanks.

**Comment by romandanylyk** [comment]
Hi @talent-webmobiledeveloper 
use this:
` pageIndicatorView.setClickListener(new DrawController.ClickListener() {
            @Override
            public void onIndicatorClicked(int position) {
                //TODO handle click
            }
        });`
