### ISSUE TITLE
setSelectedColor(int color) has no effect

### ISSUE THREAD

**Issue by heming0512** [romandanylyk/PageIndicatorView#9]
My code:
PageIndicatorView pageIndicatorView = (PageIndicatorView)findViewById(R.id.pageIndicatorView);
		pageIndicatorView.setSelectedColor(R.color.red_e6);
		pageIndicatorView.setUnselectedColor(R.color.green7e);
		pageIndicatorView.setViewPager(mViewPager);
 but has no effect .although change color ,but the effect no change .

**Comment by romandanylyk** [comment]
As I can see, you set selected/unselected color ID instead of color.
Please make use you set 
pageIndicatorView.setUnselectedColor(getResources().getColor(R.color.green7e));
