### ISSUE TITLE
compile in gradle

### ISSUE THREAD

**Issue by YakubenkoAndrii** [romandanylyk/PageIndicatorView#91]
Can you set "implementation" instead of "compile" in app.gradle ?

Configuration 'compile' is obsolete and has been replaced with 'implementation' and 'api'.
It will be removed at the end of 2018. For more information see: http://d.android.com/r/tools/update-dependency-configurations.html

**Comment by romandanylyk** [comment]
@YakubenkoAndrii Hi,
yes you can, I also updated library to have new build.gradle dependency configuration and read.me file to more have more relevant information.
Thanks for noticing this.
