### ISSUE TITLE
When to support androidx?

### ISSUE THREAD

**Issue by as11051105** [romandanylyk/PageIndicatorView#93]
When to support androidx

**Comment by hmedat** [comment]
+1

**Comment by kangjihwan** [comment]
+1

**Comment by anapsil** [comment]
+1

**Comment by kstanislav** [comment]
bump

**Comment by romandanylyk** [comment]
@kstanislav pull-request been merged and released in version [v1.0.3](https://github.com/romandanylyk/PageIndicatorView/releases/tag/v.1.0.3)
